version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: acdt-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: incidents
      MYSQL_USER: incident-user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
  webapp:
    image: acdt-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"